require 'active_support/core_ext/class/attribute_accessors'
require 'kissmetrics_http_client'
require 'application_controller'
require_relative '../config/initializers/kissmetrics_http_client'
require 'purchase'
